language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install: "pip install -rrequirements.txt; pip install -rtest_requirements.txt
# command to run tests
script: nosetests tests
